### ISSUE TITLE
Error during the video analysis

### ISSUE THREAD

**Issue by Risato-Giovanni** [ToReinberger/pyHeart4Fish#2]
Dear Dr.  Reinberger,

I hope this email finds you well. My name is Giovanni Risato, and I am a Post-Doc at the University of Padua, Italy. 
We are using your software for the analysis of zebrafish hearts for our research. It is very useful programm. We have analysied hundreds of videos without any problems, however, during the last analysis, the problem has emerged. The code returns the following message: 

Take max from temporary thresholds:  169 173 7 5 1
Threshold:  190
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 950, in _bootstrap_inner
    self.run()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\threading.py", line 888, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\user\Desktop\Programs\pyHeart4Fish_scripts\heart_beat_GUI_only_one_fish_multiprocessing.py", line 270, in start_progress_bar
    process_other_images_and_plot_hearts(self.img, params_temp)
  File "C:\Users\user\Desktop\Programs\pyHeart4Fish_scripts\heart_beat_GUI_only_one_fish_multiprocessing.py", line 901, in process_other_images_and_plot_hearts
    x_min, x_max = int(np.min(heart[1]) * 0.80), int(np.max(heart[1]) * 1.20)
  File "<__array_function__ internals>", line 5, in amin
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 2879, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\core\fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

The software cannot procceed with the analysis and give any results. 
Thank you in advance for considering our request. If you require some additional information, please do not hesitate to contact me here or by email giovanni.risato@phd.unipd.it

Best regards, 
Giovanni.

**Comment by ToReinberger** [comment]
the signal from the yalk sac seems to interfere with your analysis. Maybe try to avoid auto-fluorescence or draw the selection box a bit smaller. I try to figure out how to exclude the background noise completely in a later version. Is it also possible to increase the magnification of your movies?
